csv_split: sequential_images_split.csv
model_type: MiDaS_small # It can be DPT_Large, DPT_Hybrid or MiDaS_small
batch_size: 8
epochs: 15
lr: 0.0001
weight_decay: 0.000001
loss: Huber # It can be L1, MSE, Huber, SIL, SSIM is still WIP
log_metrics_every: 5 # Log metrics every n epochs
desired_metrics: ["accuracy_threshold", "RMSE", "RMSLE"]